### ISSUE TITLE
Message with underscore character is not sent

### ISSUE THREAD

**Issue by brainydamage** [jenkinsci/telegram-notifications-plugin#46]
Hi there!

I have multibranch pipeline and I get git commiter email this way:
```
GIT_COMMITER_EMAIL = sh(script: 
     "git --no-pager show -s --format='%ce' $GIT_COMMIT", 
     returnStdout: true).
trim()
```
Then I try to send message to telegram like this:
```
telegramSend "Build project failed! \n" +
     "Author: ${GIT_COMMITER_EMAIL} \n" +
     "Branch name: ${BRANCH_NAME}"
```

I see in Jenkins console log:
```
Post stage
[Pipeline] step
Build project failed! 
Author: user_name@domain.com
Branch name: notifications
```

But I have nothing in telegram. As soon as I comment the line contains ${GIT_COMMITER_EMAIL}, message is sent correctly.

I tried to hardcode my email instead of using variable - the result is the same: message is not sent without any errors. 

Thanks in advance
Best regards!

**Comment by brainydamage** [comment]
The problem is in underscore character. When there is no underscore characters in string, message is sent correctly.
Jenkins log:
`org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 26`
26 is the position of '_' char.

**Comment by brainydamage** [comment]
I've fixed the issue this way. Replace all '_' chars by '\\_' chars (escape underscore symbol):  
```
GIT_COMMITER_EMAIL = sh(script: 
     "git --no-pager show -s --format='%ce' $GIT_COMMIT", 
     returnStdout: true).
trim().replaceAll("_", "\\\\_")
```

**Comment by leomachado73** [comment]
Hey, in case someone's still having this problem, I used this solution and it worked perfectly:

example:
String originalMessage = "Install of branch [develop_1] has finished with SUCCESS"
String escapedMessage = originalMessage
                 .replace("_", "\\_")
                 .replace("*", "\\*")
                 .replace("[", "\\[")
                 .replace("`", "\\`");

               telegramSend escapedMessage
